DROP TABLE if EXISTS line CASCADE;

DROP TABLE if EXISTS station CASCADE;

DROP TABLE if EXISTS section CASCADE;

CREATE TABLE line (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    color VARCHAR(255),
    distance bigint,
    down_station_id bigint,
    name VARCHAR(255),
    up_station_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE station (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE section (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    distance bigint,
    down_station_id bigint,
    line_id bigint,
    up_station_id bigint,
    PRIMARY KEY (id)
);
