### 지하철역 생성
POST http://localhost:8080/stations
Content-Type: application/json
Accept: application/json
Content-Length: 118

{
  "name": "판교역"
}


### 지하철역 목록
GET http://localhost:8080/stations
Accept: application/json


### 지하철역 삭제
DELETE http://localhost:8080/stations/1