TRUNCATE TABLE STATION;
TRUNCATE TABLE LINE;

INSERT INTO STATION (ID, NAME) VALUES (1, '강남역');
INSERT INTO STATION (ID, NAME) VALUES (2, '망포역');
INSERT INTO STATION (ID, NAME) VALUES (3, '정자역');
INSERT INTO STATION (ID, NAME) VALUES (4, '판교역');
