CREATE TABLE line (
    id bigint generated by default as identity,
    name varchar(255),
    color varchar(255),
    up_station_id bigint,
    down_station_id bigint,
    distance int4,
    primary key (id)
);

CREATE UNIQUE INDEX line_name_uk ON line(name);
