CREATE TABLE if not exists line (
    line_id bigint generated by default as identity,
    name varchar(255),
    color varchar(255),
    primary key (line_id)
);

CREATE TABLE if not exists section (
    section_id bigint generated by default as identity,
    up_station_id bigint,
    down_station_id bigint,
    distance int4,
    line_id int8,
    primary key (section_id)
);

CREATE UNIQUE INDEX if not exists line_name_uk ON line(name);
