CREATE TABLE if not exists station (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

CREATE UNIQUE INDEX if not exists station_name_uk ON station(name);
