SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE STATION;
TRUNCATE TABLE SUBWAY_LINE;
ALTER TABLE STATION ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE SUBWAY_LINE ALTER COLUMN ID RESTART WITH 1;
SET REFERENTIAL_INTEGRITY TRUE;