create table line (
                      line_id bigint generated by default as identity,
                      line_name varchar(255),
                      color varchar(255),
                      up_station_id bigint,
                      down_station_id bigint,
                      line_distance integer,
                      primary key (line_id)
);

create table station (
                         station_id bigint generated by default as identity,
                         station_name varchar(20) not null,
                         primary key (station_id)
);

create table section(
                        section_id bigint generated by default as identity,
                        line_id bigint,
                        up_station_id bigint,
                        down_station_id bigint,
                        section_distance integer
)