INSERT INTO LINE VALUES(1, '2호선', '#00008C', 1, 3, 10);

INSERT INTO STATION VALUES(1, '강남역');
INSERT INTO STATION VALUES(2, '역삼역');
INSERT INTO STATION VALUES(3, '선릉역');
INSERT INTO STATION VALUES(4, '삼성역');

INSERT INTO SECTION VALUES(100, 1, 1, 2, 7);
INSERT INTO SECTION VALUES(101, 1, 2, 3, 3);