SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE line;
TRUNCATE TABLE station;
TRUNCATE TABLE LINE_END_STATIONS;
ALTER TABLE line ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE station ALTER COLUMN ID RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;