SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE end_stations;
TRUNCATE TABLE end_stations_stations;
TRUNCATE TABLE line;
TRUNCATE TABLE station;
ALTER TABLE end_stations ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE line ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE station ALTER COLUMN ID RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;