SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE line;
TRUNCATE TABLE station;
ALTER TABLE line ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE station ALTER COLUMN ID RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;