SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE station_to_subway_line RESTART IDENTITY;
TRUNCATE TABLE station RESTART IDENTITY;
TRUNCATE TABLE subway_line RESTART IDENTITY;
TRUNCATE TABLE subway_line_color RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;
