DELETE FROM STATION;
DELETE FROM SECTION;
DELETE FROM LINE;
ALTER TABLE SECTION ALTER COLUMN SECTION_ID RESTART WITH 1;
ALTER TABLE LINE ALTER COLUMN LINE_ID RESTART WITH 1;
ALTER TABLE STATION ALTER COLUMN ID RESTART WITH 1;

INSERT INTO STATION (id, name) VALUES (1, '강남역');
INSERT INTO STATION (id, name) VALUES (2, '미금역');
INSERT INTO STATION (id, name) VALUES (3, '오리역');
INSERT INTO STATION (id, name) VALUES (4, '판교역');
INSERT INTO STATION (id, name) VALUES (5, '정자역');
INSERT INTO STATION (id, name) VALUES (6, '동천역');