SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE LINE_STATION_MAP;
TRUNCATE TABLE LINE;
TRUNCATE TABLE STATION;
ALTER TABLE LINE_STATION_MAP ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE LINE ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE STATION ALTER COLUMN ID RESTART WITH 1;
SET REFERENTIAL_INTEGRITY TRUE;
