SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE LINE;
TRUNCATE TABLE STATION;
TRUNCATE TABLE SECTION;

ALTER TABLE LINE ALTER COLUMN id RESTART WITH 1;
ALTER TABLE STATION ALTER COLUMN id RESTART WITH 1;
ALTER TABLE SECTION ALTER COLUMN id RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;