SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE LINE;
TRUNCATE TABLE STATION;

ALTER TABLE LINE ALTER COLUMN id RESTART WITH 1;
ALTER TABLE STATION ALTER COLUMN id RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;