SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE STATION;
TRUNCATE TABLE LINE;
SET REFERENTIAL_INTEGRITY TRUE;

INSERT INTO STATION (id, name) VALUES (1, '지하철역');
INSERT INTO STATION (id, name) VALUES (2, '새로운 지하철역');
INSERT INTO STATION (id, name) VALUES (3, '또 다른 지하철역');
